name: mangiaescappa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.80108
title: Mangia e Scappa Italian Foods Ltd.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#13111e'
    - '#eae8f6'
    - '#914f50'
    - '#a19aac'
    - '#334c22'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
