name: mangiaescappa
favicon: null
layout_spectrum: 0
typography_spectrum: 0.10869
title: Mangia e Scappa Italian Foods Ltd.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7293b4'
    - '#c3e7ff'
    - '#0f1211'
    - '#585045'
    - '#d67753'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
