title: Mangia e Scappa Italian Foods Ltd.
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 1
  lightness: 0.5
  brandColors:
    - '#7293b4'
    - '#c3e7ff'
    - '#0f1211'
    - '#585045'
    - '#d67753'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: mangiaescappa
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9892473
layout_spectrum: 1
